### PR TITLE
unify the trace functions of numerical and analytical fields

### PR DESCRIPTION
**Pull request by TCLiuu**
1. I have modified the getinterp function to a closure function to return a field function which is similar to analytical field. Meanwhile, those redundant functions were deleted.
2. Fixing the function names in the test sets.
3. Adding a type judgement to prepare function for supporting the mixture of different type of fields.
4. Adding a simple test set about mixed fields.

### CODE REVIEW

**Comment by henry2004y** [comment]
1. We can remove empty lines after function (e.g. Line 20, 32, 45, 78, 96, 116).
2. In `runtests.jl`, "mixed fields" sounds confusing to me at first. Maybe "mixed type fields"?
3. Since we are unifying the functions, we can add tests for the relativistic cases. I don't even know if the original implementation is correct.

**Comment by TCLiuu** [comment]
> 1. We can remove empty lines after function (e.g. Line 20, 32, 45, 78, 96, 116).
> 2. In `runtests.jl`, "mixed fields" sounds confusing to me at first. Maybe "mixed type fields"?
> 3. Since we are unifying the functions, we can add tests for the relativistic cases. I don't even know if the original implementation is correct.
> 4. We aim for improving test coverage. Check the reports on this page and the detailed line report in the File Changed tag.
> 5. Maybe it's nice to have some benchmarks as well (in another PR). Checkout, for example, [PkgBenchmark](https://github.com/JuliaCI/PkgBenchmark.jl). For this PR, report some profiling results here?

I will correct this problems and rename the test set. PkgBenchmark sounds very interesting.
And for a PR,  are there some rules about test and its coverage?

**Comment by TCLiuu** [comment]
update:
1. Fixing some problems.
2. Adding a test set including external field F which replaces the former one. And fix a bug in `trace_full`.

**Comment by henry2004y** [comment]
> And for a PR, are there some rules about test and its coverage?

Most of the time, we should increase test coverage. For new features, they should always be associated with new tests.

**Comment by henry2004y** [comment]
Are you planning to have tests for relativistic cases in another PR?

**Pull request merged**
