### PR TITLE
Add an example based on magnetic mirror 

### PR DESCRIPTION
**Pull request by TCLiuu**
1. Fixed a serious bug related to  magnetic field calculation of magnetic mirror.
This bug will cause serious divergence at the center axis of the magnetic field. #73 may require recalculating the relevant calculations involving magnetic mirrors.

2. Add  a new example base on a magnetic mirror.
image
From the third figure on the right, it can be seen that the zero-order quantity of magnetic moment is conserved, but its high-order part is not conserved under this definition of magnetic moment and oscillates rapidly. We can observe from this the oscillation characteristics of magnetic moments at different levels.

The bug fixed in the first item will cause magnetic moment non-conservation, as mentioned in #72.

### CODE REVIEW

**Comment by henry2004y** [comment]
From the figure, we see that the high-frequency oscillation of the magnetic moment is caused by the oscillation in the magnetic field strength. Is it due to the numerical accuracy of B calculation (especially `ellipke`)? I guess a 0.5% diff (0.01 / 1.9) is acceptable in this case.

**Comment by TCLiuu** [comment]
> From the figure, we see that the high-frequency oscillation of the magnetic moment is caused by the oscillation in the magnetic field strength. Is it due to the numerical accuracy of B calculation (especially `ellipke`)? I guess a 0.5% diff (0.01 / 1.9) is acceptable in this case.

Sorry, I don't quite understand what you mean. The variation in magnetic field strength here is normal, and the magnetic field in the magnetic mirror changes slowly with space. The magnetic moment also varies with changes in the magnetic field strength, which I believe is also normal. The condition for the invariant of the magnetic moment is that the magnetic field changes slowly, meaning that it only holds at zero order on a time scale of slow change. Therefore, the magnetic moment will vary with changes in the magnetic field. I think the accuracy of magnetic field calculation may not be related to this. Perhaps I misunderstood your meaning?

**Comment by henry2004y** [comment]
What confuses me a bit is the small spikes near the peaks and troughs in B strength. Compared to that, $v_\perp$ looks much smoother. Since the magnetic field in the mirror should vary slowly, I am not sure why we are getting those spikes. These small spikes also take place between the peaks and troughs.

**Comment by TCLiuu** [comment]
This is an enlarged figure:
image
I think that these fluctuations are caused by the particle's gyration, and the magnetic field here is what the particles see rather than what the guiding center sees. Therefore, even if the magnetic field changes slowly in space, there will still be some high-frequency terms generated due to the particle's gyration, which corresponds to the high-frequency part of magnetic moment variation. This also explains why vertical velocity is smoother because a particle's energy remains approximately constant during one gyration cycle.

**Pull request merged**
