### PR TITLE
Remove extrapolate

### PR DESCRIPTION
**Pull request by henry2004y**
Handle #68

### CODE REVIEW

**Comment by henry2004y** [comment]
This is too strange. With Julia 1.9-rc1 I found even larger regression for the in-place numerical tracing. Will open another issue.

**Comment by TCLiuu** [comment]
> This is too strange. With Julia 1.9-rc1 I found even larger regression for the in-place numerical tracing. Will open another issue.

It is very interesting. Is this related to the CPU architecture you are using? I remember you mentioned before that the results on your M-series Mac were different from those on x86 platforms.

**Comment by TCLiuu** [comment]
Also, have you tested the improvement of first-time-to-plot in this project with Julia 1.9?

**Comment by henry2004y** [comment]
I am using Ubuntu with Intel chips. I had a GC issue posted in #27, but that one is probably not specific to Julia 1.9-rc1; I got the same GC issue with Julia 1.8.5.

**Comment by TCLiuu** [comment]
> I am using Ubuntu with Intel chips. The issue with ARM-based MAC is the slightly different accuracy.
> 
> https://github.com/henry2004y/TestParticle.jl/blob/66a8cbec9d976c06c4ab69c751183ea591ee8752/test/runtests.jl#L63
> 
> 
> I had a GC issue posted in #27, but that one is probably not specific to Julia 1.9-rc1; I got the same GC issue with Julia 1.8.5.

I ran the same benchmark under Julia 1.8.0 and posted the results in #27. The operating platform is Ubuntu.

**Comment by TCLiuu** [comment]
Based on the code in this PR, I ran a benchmark under julia1.8.0 and obtained the following results. The platform used was Ubuntu with an AMD CPU.
| ID                                                  | time           | GC time | memory         | allocations |
|-----------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`           |  6.747 μs (5%) |         | 14.02 KiB (1%) |         157 |
| `["trace", "analytic field", "out of place"]`       |  5.654 μs (5%) |         | 12.31 KiB (1%) |         133 |
| `["trace", "numerical field", "in place"]`          | 17.312 μs (5%) |         | 27.08 KiB (1%) |         175 |
| `["trace", "numerical field", "out of place"]`      | 13.605 μs (5%) |         | 21.45 KiB (1%) |         147 |
| `["trace", "time-dependent field", "in place"]`     |  8.075 μs (5%) |         | 15.22 KiB (1%) |         172 |
| `["trace", "time-dependent field", "out of place"]` |  6.899 μs (5%) |         | 13.52 KiB (1%) |         148 |

**Comment by henry2004y** [comment]
So your results are identical in terms of memory usage with the old extrapolate method? Hmm, I will check again later.

**Pull request closed without merging**
